language: python
python:
  - '3.7'
branches:
  only:
    - develop
install:
  - pip install -r requirements.txt
  - pip install ghp-import
script:
  - make publish
  - ghp-import output -b gh-pages
deploy:
  provider: pages
  repo: rihbyne/rihbyne.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
