language: python
sudo: false
python:
- '3.6'
before_script:
- git config --global user.email "rihen234@gmail.com"
- git config --global user.name "Rihan Pereira"
- git remote rm origin
- git remote add origin https://user:${GITHUB_TOKEN}@github.com/rihbyne/rihbyne.github.io.git
branches:
  only:
  - develop
install:
- pip install -r requirements.txt
- pip install ghp-import
script:
- make publish
- ghp-import output -b gh-pages
deploy:
  provider: pages
  repo: rihbyne/rihbyne.github.io
  target_branch: master
  skip_cleanup: true
  keep_history: true
  github_token: "$GITHUB_TOKEN"
  local_dir: output
  on:
    branch: develop
env:
  global:
    secure: VOo7Bi7eUkMJVmnR4dKOOEqSZw1g4gygHqVAjcFKkP+j+osiCmslr2WVhWGZBv7ilo7SRuX+PtwbMy9VmhTEbHie8OjD9Q75Bzl3hcRDTBjrf8Pfwt+BG36coS8Hfi9Kf6Jg7FuuU58jm3QjoEglgYM8HEE5kYQXBgbyKXPCLJZqPNpTjqJRRoyQpzS2bGhk+UvG79r7kDCtdKjd5TgYCpiwO1nnCyBZtaMUbf+/L9avRR1MUvnwsYxvPGXQUAjdsCWQet7NeyUTz1Hsg9NuFBptfpZfBOgk2YJ2AobaWM2niZBQcSG+jI7uCichNuOQaMMag5abdPCeOkXTpfZuGVVJs5Qt9DLr2BWwlljfjnhi0XjVLjRzHZHqXvGM9sAw0pLbcsiUyNINhx9u81CEZc/oIhq8P8fXkfl9eTqHwtwPjiynwWIBNGX31LzzB+oP9Zygy2q1RjPSwj0Diyu762v/s4njCgS/yidkYFCcsc/nvg51rPW8KjJUrwKhsd9pfrrS+QjAoyPk33SbJVHQRCdfR7WXPUcqRGaHfrY96I7D5CqsPianANYLmuRcJMWoRJO2JywSL2PHAbW9hDnn/3MKrDjWSKUNvD9McTndSqrpnRH6ZcBNOgX2S5FFAU2P1omJNqXQHh1XcWe/eauNxLj7K1JHj4nAr2kvhTRtPR8=
