language: python
python:
  - '3.7'
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - make publish
deploy:
  provider: pages
  repo: rihbyne/rihbyne.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
